package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/Emilia-Poleszak/Token_Transfer_API/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)


func (r *mutationResolver) Transfer(ctx context.Context, from_address string, to_address string, amount int32) (int32, error) {
	var from_wallet_balance int32
	
	if amount <= 0 {
		return 0, fmt.Errorf("Invalid amount: must be > 0.")
	}

	err := r.DB.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
	
		var fromWallet, toWallet models.Wallet
		first, second := from_address, to_address
		reversed := false
		var wallets []models.Wallet

		// Use consistent ordering to prevent deadlocks	
		if second < first{
			first, second = second, first
			reversed = true
		} 

		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).
		Where("address IN ?", []string{first, second}).
		Order("address").
		Find(&wallets).Error; err != nil {
			return fmt.Errorf("Error fetching wallets: %w", err)
		}

		if reversed {
			fromWallet, toWallet = wallets[1], wallets[0]
		} else {
			fromWallet, toWallet = wallets[0], wallets[1]
		}

		if errorNotFound := tx.Where("address = ?", from_address).First(&models.Wallet{}).Error; errorNotFound == gorm.ErrRecordNotFound {
			return fmt.Errorf("From wallet not found")
		}

		errorNotFound2 := tx.Where("address = ?", to_address).First(&models.Wallet{}).Error
		
		if errorNotFound2 == gorm.ErrRecordNotFound {
			toWallet = models.Wallet{Address: to_address, Balance: 0}
			
			if err := tx.Create(&toWallet).Error; err != nil {
				return fmt.Errorf("Error creating to wallet: %w", err)
			}
		} else if errorNotFound2 != nil {
			return fmt.Errorf("Error fetching to wallet: %w", errorNotFound2)
		}

		if fromWallet.Balance < amount {
			return fmt.Errorf("Insufficient balance")
		}

		fromWallet.Balance -= amount
		toWallet.Balance += amount

		if err := tx.Save(&fromWallet).Error; err != nil {
			return fmt.Errorf("From wallet update failed: %w", err)
		}

		if err := tx.Save(&toWallet).Error; err != nil {
			return fmt.Errorf("To wallet update failed: %w", err)
		}

		from_wallet_balance = fromWallet.Balance
		return nil
	})

	return from_wallet_balance, err
}


// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
