package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/Emilia-Poleszak/Token_Transfer_API/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)


func (r *mutationResolver) Transfer(ctx context.Context, from_address string, to_address string, amount int32) (int32, error) {
	if amount <= 0 {
		return 0, fmt.Errorf("Invalid amount: must be > 0.")
	}

	tx := r.DB.WithContext(ctx).Begin()
	if tx.Error != nil {
		return 0, fmt.Errorf("Transaction start failed: %w", tx.Error)
	}

	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
			panic(r)
		}
	}()

	var fromWallet, toWallet models.Wallet

	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("address = ?", from_address).First(&fromWallet).Error; err != nil {
		tx.Rollback()
		
		if err == gorm.ErrRecordNotFound {
			return 0, fmt.Errorf("From wallet not found")
		}
		
		return 0, fmt.Errorf("Error fetching from wallet: %w", err)
	}

	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where("address = ?", to_address).First(&toWallet).Error; err != nil {
		tx.Rollback()
		
		if err == gorm.ErrRecordNotFound {
			return 0, fmt.Errorf("To wallet not found")
		}
		
		return 0, fmt.Errorf("Error fetching to wallet: %w", err)
	}

	if fromWallet.Balance < amount {
		tx.Rollback()
		return 0, fmt.Errorf("Insufficient balance")
	}

	fromWallet.Balance -= amount
	toWallet.Balance += amount

	if err := tx.Save(&fromWallet).Error; err != nil {
		tx.Rollback()
		return 0, fmt.Errorf("From wallet update failed: %w", err)
	}

	if err := tx.Save(&toWallet).Error; err != nil {
		tx.Rollback()
		return 0, fmt.Errorf("To wallet update failed: %w", err)
	}

	if err := tx.Commit().Error; err != nil {
		tx.Rollback()
		return 0, fmt.Errorf("Transaction failed: %w", err)
	}

	return fromWallet.Balance, nil
}


// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
